//go:build linux

package autostart

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func unitPath() string {
	return filepath.Join(home(), ".config/systemd/user/marble-peer.service")
}

func wrapperPath() string {
	return filepath.Join(home(), ".local/bin/marble-peer-session")
}

func desktopPath() string {
	return filepath.Join(home(), ".config/autostart/marble-peer.desktop")
}

func installLinux(exe string, enable bool) ([]string, string, error) {
	var written []string

	// Session wrapper: inject DISPLAY / bus for tray + desktop tools under systemd --user.
	wrapDir := filepath.Dir(wrapperPath())
	if err := os.MkdirAll(wrapDir, 0o755); err != nil {
		return nil, "", err
	}
	wrapper := fmt.Sprintf(`#!/usr/bin/env bash
# Generated by marble-peer install-autostart — starts peer with a graphical session env.
set -euo pipefail
export HOME="${HOME:-%s}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=${XDG_RUNTIME_DIR}/bus}"
export PATH="${HOME}/.local/bin:/usr/local/bin:/usr/bin:/bin:${PATH:-}"

# Prefer existing session display; fall back to :0 / wayland-0 (common on Ubuntu).
if [ -z "${DISPLAY:-}" ]; then
  if [ -S /tmp/.X11-unix/X0 ]; then
    export DISPLAY=:0
  elif [ -S /tmp/.X11-unix/X1 ]; then
    export DISPLAY=:1
  fi
fi
if [ -z "${WAYLAND_DISPLAY:-}" ] && [ -S "${XDG_RUNTIME_DIR}/wayland-0" ]; then
  export WAYLAND_DISPLAY=wayland-0
fi
if [ -z "${XAUTHORITY:-}" ] && [ -f "${HOME}/.Xauthority" ]; then
  export XAUTHORITY="${HOME}/.Xauthority"
fi

# Log directory
mkdir -p "${HOME}/.marble-peer"
exec %q run "$@"
`, home(), exe)
	if err := os.WriteFile(wrapperPath(), []byte(wrapper), 0o755); err != nil {
		return nil, "", err
	}
	written = append(written, wrapperPath())

	unitDir := filepath.Dir(unitPath())
	if err := os.MkdirAll(unitDir, 0o755); err != nil {
		return nil, "", err
	}
	logPath := filepath.Join(home(), ".marble-peer/peer.log")
	unit := fmt.Sprintf(`[Unit]
Description=Marble desktop peer (computer use agent)
Documentation=https://github.com/rendicott/marble-desktop-peer
After=graphical-session.target network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=%s
Restart=on-failure
RestartSec=5
# Clean exit from tray Quit should not loop-restart
RestartPreventExitStatus=0
KillMode=control-group
TimeoutStopSec=15
# Session-ish defaults (wrapper also fills DISPLAY/bus)
Environment=PATH=%s/.local/bin:/usr/local/bin:/usr/bin:/bin
Environment=HOME=%s
Environment=XDG_RUNTIME_DIR=/run/user/%%U
# Keep display/session awake while peer runs (marble-peer also inhibits idle)
Environment=MARBLE_PEER_KEEP_AWAKE=1
StandardOutput=append:%s
StandardError=append:%s

[Install]
WantedBy=default.target
`, wrapperPath(), home(), home(), logPath, logPath)
	if err := os.WriteFile(unitPath(), []byte(unit), 0o644); err != nil {
		return nil, "", err
	}
	written = append(written, unitPath())

	// Desktop autostart as backup when user session doesn't pull default.target units early.
	// Only starts if not already running (peer single-instance lock).
	deskDir := filepath.Dir(desktopPath())
	if err := os.MkdirAll(deskDir, 0o755); err != nil {
		return nil, "", err
	}
	desktop := fmt.Sprintf(`[Desktop Entry]
Type=Application
Version=1.0
Name=Marble Peer
Comment=Desktop agent for Marble (computer use)
Exec=%s
Icon=utilities-terminal
Terminal=false
Categories=Utility;Network;
X-GNOME-Autostart-enabled=true
StartupNotify=false
`, wrapperPath())
	if err := os.WriteFile(desktopPath(), []byte(desktop), 0o644); err != nil {
		return nil, "", err
	}
	written = append(written, desktopPath())

	msg := "wrote systemd unit + session wrapper + desktop autostart"
	if enable {
		if out, err := run("systemctl", "--user", "daemon-reload"); err != nil {
			return written, msg, fmt.Errorf("daemon-reload: %v (%s)", err, out)
		}
		if out, err := run("systemctl", "--user", "enable", "--now", "marble-peer.service"); err != nil {
			// enable may succeed while start fails (not paired yet) — still report
			return written, msg + "\nenable/start: " + out, fmt.Errorf("enable --now: %v (%s)", err, out)
		}
		st, _ := run("systemctl", "--user", "is-active", "marble-peer.service")
		msg += "\nenabled and started (active=" + st + ")"
		msg += "\nlogs: journalctl --user -u marble-peer -f"
		msg += "\n      tail -f " + logPath
	} else {
		msg += "\nenable with: systemctl --user daemon-reload && systemctl --user enable --now marble-peer"
	}
	return written, msg, nil
}

func uninstallLinux() ([]string, string, error) {
	var removed []string
	_, _ = run("systemctl", "--user", "disable", "--now", "marble-peer.service")
	for _, p := range []string{unitPath(), wrapperPath(), desktopPath()} {
		if err := os.Remove(p); err == nil {
			removed = append(removed, p)
		}
	}
	_, _ = run("systemctl", "--user", "daemon-reload")
	msg := "disabled marble-peer.service and removed " + strings.Join(removed, ", ")
	if len(removed) == 0 {
		msg = "nothing to remove (already uninstalled?)"
	}
	return removed, msg, nil
}
